/*
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected MyDslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_AtomicTask_RobotKeyword_3_1_or_RobotsKeyword_3_0;
	protected AbstractElementAlias match_Mission_ParametersKeyword_6_0_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (MyDslGrammarAccess) access;
		match_AtomicTask_RobotKeyword_3_1_or_RobotsKeyword_3_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getAtomicTaskAccess().getRobotKeyword_3_1()), new TokenAlias(false, false, grammarAccess.getAtomicTaskAccess().getRobotsKeyword_3_0()));
		match_Mission_ParametersKeyword_6_0_q = new TokenAlias(false, true, grammarAccess.getMissionAccess().getParametersKeyword_6_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_AtomicTask_RobotKeyword_3_1_or_RobotsKeyword_3_0.equals(syntax))
				emit_AtomicTask_RobotKeyword_3_1_or_RobotsKeyword_3_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Mission_ParametersKeyword_6_0_q.equals(syntax))
				emit_Mission_ParametersKeyword_6_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'robots' | 'robot'
	 *
	 * This ambiguous syntax occurs at:
	 *     robots=EInt (ambiguity) 'needed' ',' retry=EInt
	 *     robots=EInt (ambiguity) 'needed' 'at' 'location' loc=[Location|EString]
	 *     robots=EInt (ambiguity) 'needed' (rule end)
	 
	 * </pre>
	 */
	protected void emit_AtomicTask_RobotKeyword_3_1_or_RobotsKeyword_3_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'parameters:'?
	 *
	 * This ambiguous syntax occurs at:
	 *     constraints+=Constraints (ambiguity) (rule end)
	 *     obj+=Objective (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_Mission_ParametersKeyword_6_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
