/*
 * generated by Xtext 2.30.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getWorldModelAccess().getAlternatives(), "rule__WorldModel__Alternatives");
			builder.put(grammarAccess.getTasksModelAccess().getAlternatives(), "rule__TasksModel__Alternatives");
			builder.put(grammarAccess.getAtomicTaskAccess().getAlternatives_3(), "rule__AtomicTask__Alternatives_3");
			builder.put(grammarAccess.getCompoundTaskAccess().getAlternatives_6(), "rule__CompoundTask__Alternatives_6");
			builder.put(grammarAccess.getMissionTaskAccess().getAlternatives_3(), "rule__MissionTask__Alternatives_3");
			builder.put(grammarAccess.getConstraintsAccess().getAlternatives(), "rule__Constraints__Alternatives");
			builder.put(grammarAccess.getSpaceXYRobotAccess().getAlternatives_0(), "rule__SpaceXYRobot__Alternatives_0");
			builder.put(grammarAccess.getTaskTimeAccess().getAlternatives_0(), "rule__TaskTime__Alternatives_0");
			builder.put(grammarAccess.getAllocateTAccess().getAlternatives_1(), "rule__AllocateT__Alternatives_1");
			builder.put(grammarAccess.getAllocateTAccess().getAlternatives_3(), "rule__AllocateT__Alternatives_3");
			builder.put(grammarAccess.getClosestAccess().getAlternatives_2(), "rule__Closest__Alternatives_2");
			builder.put(grammarAccess.getMaxTasksAccess().getAlternatives_5(), "rule__MaxTasks__Alternatives_5");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
			builder.put(grammarAccess.getObjectiveAccess().getAlternatives(), "rule__Objective__Alternatives");
			builder.put(grammarAccess.getXYAccess().getAlternatives(), "rule__XY__Alternatives");
			builder.put(grammarAccess.getLowerGreaterAccess().getAlternatives(), "rule__LowerGreater__Alternatives");
			builder.put(grammarAccess.getStartEndAccess().getAlternatives(), "rule__StartEnd__Alternatives");
			builder.put(grammarAccess.getProblemSpecificationAccess().getGroup(), "rule__ProblemSpecification__Group__0");
			builder.put(grammarAccess.getProblemSpecificationAccess().getGroup_9(), "rule__ProblemSpecification__Group_9__0");
			builder.put(grammarAccess.getProblemSpecificationAccess().getGroup_13(), "rule__ProblemSpecification__Group_13__0");
			builder.put(grammarAccess.getProblemSpecificationAccess().getGroup_17(), "rule__ProblemSpecification__Group_17__0");
			builder.put(grammarAccess.getLocationAccess().getGroup(), "rule__Location__Group__0");
			builder.put(grammarAccess.getLocationAccess().getGroup_7(), "rule__Location__Group_7__0");
			builder.put(grammarAccess.getPathsAccess().getGroup(), "rule__Paths__Group__0");
			builder.put(grammarAccess.getPathsAccess().getGroup_6(), "rule__Paths__Group_6__0");
			builder.put(grammarAccess.getAtomicTaskAccess().getGroup(), "rule__AtomicTask__Group__0");
			builder.put(grammarAccess.getAtomicTaskAccess().getGroup_5(), "rule__AtomicTask__Group_5__0");
			builder.put(grammarAccess.getAtomicTaskAccess().getGroup_6(), "rule__AtomicTask__Group_6__0");
			builder.put(grammarAccess.getCompoundTaskAccess().getGroup(), "rule__CompoundTask__Group__0");
			builder.put(grammarAccess.getCompoundTaskAccess().getGroup_4(), "rule__CompoundTask__Group_4__0");
			builder.put(grammarAccess.getCompoundTaskAccess().getGroup_4_1(), "rule__CompoundTask__Group_4_1__0");
			builder.put(grammarAccess.getCompoundTaskAccess().getGroup_6_0(), "rule__CompoundTask__Group_6_0__0");
			builder.put(grammarAccess.getCompoundTaskAccess().getGroup_6_1(), "rule__CompoundTask__Group_6_1__0");
			builder.put(grammarAccess.getRobotAccess().getGroup(), "rule__Robot__Group__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_13(), "rule__Robot__Group_13__0");
			builder.put(grammarAccess.getCapabilityAccess().getGroup(), "rule__Capability__Group__0");
			builder.put(grammarAccess.getMissionAccess().getGroup(), "rule__Mission__Group__0");
			builder.put(grammarAccess.getMissionAccess().getGroup_1(), "rule__Mission__Group_1__0");
			builder.put(grammarAccess.getMissionAccess().getGroup_4(), "rule__Mission__Group_4__0");
			builder.put(grammarAccess.getMissionAccess().getGroup_5(), "rule__Mission__Group_5__0");
			builder.put(grammarAccess.getMissionAccess().getGroup_5_2(), "rule__Mission__Group_5_2__0");
			builder.put(grammarAccess.getMissionAccess().getGroup_6(), "rule__Mission__Group_6__0");
			builder.put(grammarAccess.getMissionAccess().getGroup_6_1(), "rule__Mission__Group_6_1__0");
			builder.put(grammarAccess.getMissionAccess().getGroup_6_2(), "rule__Mission__Group_6_2__0");
			builder.put(grammarAccess.getMissionAccess().getGroup_6_3(), "rule__Mission__Group_6_3__0");
			builder.put(grammarAccess.getMissionAccess().getGroup_6_4(), "rule__Mission__Group_6_4__0");
			builder.put(grammarAccess.getMissionTaskAccess().getGroup(), "rule__MissionTask__Group__0");
			builder.put(grammarAccess.getMissionTaskAccess().getGroup_3_0(), "rule__MissionTask__Group_3_0__0");
			builder.put(grammarAccess.getMissionTaskAccess().getGroup_3_1(), "rule__MissionTask__Group_3_1__0");
			builder.put(grammarAccess.getMissionTaskAccess().getGroup_4(), "rule__MissionTask__Group_4__0");
			builder.put(grammarAccess.getRateSuccAccess().getGroup(), "rule__RateSucc__Group__0");
			builder.put(grammarAccess.getRateSuccAccess().getGroup_1(), "rule__RateSucc__Group_1__0");
			builder.put(grammarAccess.getSpaceXYRobotAccess().getGroup(), "rule__SpaceXYRobot__Group__0");
			builder.put(grammarAccess.getSpaceXYRobotAccess().getGroup_0_0(), "rule__SpaceXYRobot__Group_0_0__0");
			builder.put(grammarAccess.getSpaceXYRobotAccess().getGroup_0_1(), "rule__SpaceXYRobot__Group_0_1__0");
			builder.put(grammarAccess.getTaskTimeAccess().getGroup(), "rule__TaskTime__Group__0");
			builder.put(grammarAccess.getTaskTimeAccess().getGroup_0_0(), "rule__TaskTime__Group_0_0__0");
			builder.put(grammarAccess.getTaskTimeAccess().getGroup_0_1(), "rule__TaskTime__Group_0_1__0");
			builder.put(grammarAccess.getTaskTimeAccess().getGroup_0_2(), "rule__TaskTime__Group_0_2__0");
			builder.put(grammarAccess.getAllocateTAccess().getGroup(), "rule__AllocateT__Group__0");
			builder.put(grammarAccess.getAllocateTAccess().getGroup_1_0(), "rule__AllocateT__Group_1_0__0");
			builder.put(grammarAccess.getAllocateTAccess().getGroup_1_1(), "rule__AllocateT__Group_1_1__0");
			builder.put(grammarAccess.getAllocateTAccess().getGroup_1_2(), "rule__AllocateT__Group_1_2__0");
			builder.put(grammarAccess.getAllocateTAccess().getGroup_3_0(), "rule__AllocateT__Group_3_0__0");
			builder.put(grammarAccess.getAllocateTAccess().getGroup_3_1(), "rule__AllocateT__Group_3_1__0");
			builder.put(grammarAccess.getClosestAccess().getGroup(), "rule__Closest__Group__0");
			builder.put(grammarAccess.getClosestAccess().getGroup_2_0(), "rule__Closest__Group_2_0__0");
			builder.put(grammarAccess.getClosestAccess().getGroup_2_1(), "rule__Closest__Group_2_1__0");
			builder.put(grammarAccess.getClosestAccess().getGroup_2_2(), "rule__Closest__Group_2_2__0");
			builder.put(grammarAccess.getClosestAccess().getGroup_2_3(), "rule__Closest__Group_2_3__0");
			builder.put(grammarAccess.getMaxTasksAccess().getGroup(), "rule__MaxTasks__Group__0");
			builder.put(grammarAccess.getMaxTasksAccess().getGroup_5_0(), "rule__MaxTasks__Group_5_0__0");
			builder.put(grammarAccess.getMaxTasksAccess().getGroup_5_1(), "rule__MaxTasks__Group_5_1__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
			builder.put(grammarAccess.getProblemSpecificationAccess().getWorldModelAssignment_4(), "rule__ProblemSpecification__WorldModelAssignment_4");
			builder.put(grammarAccess.getProblemSpecificationAccess().getWorldModelAssignment_5(), "rule__ProblemSpecification__WorldModelAssignment_5");
			builder.put(grammarAccess.getProblemSpecificationAccess().getTasksModelAssignment_8(), "rule__ProblemSpecification__TasksModelAssignment_8");
			builder.put(grammarAccess.getProblemSpecificationAccess().getTasksModelAssignment_9_1(), "rule__ProblemSpecification__TasksModelAssignment_9_1");
			builder.put(grammarAccess.getProblemSpecificationAccess().getRobotsModelAssignment_12(), "rule__ProblemSpecification__RobotsModelAssignment_12");
			builder.put(grammarAccess.getProblemSpecificationAccess().getRobotsModelAssignment_13_1(), "rule__ProblemSpecification__RobotsModelAssignment_13_1");
			builder.put(grammarAccess.getProblemSpecificationAccess().getMissionAssignment_16(), "rule__ProblemSpecification__MissionAssignment_16");
			builder.put(grammarAccess.getProblemSpecificationAccess().getMissionAssignment_17_1(), "rule__ProblemSpecification__MissionAssignment_17_1");
			builder.put(grammarAccess.getLocationAccess().getNameAssignment_0(), "rule__Location__NameAssignment_0");
			builder.put(grammarAccess.getLocationAccess().getXAssignment_4(), "rule__Location__XAssignment_4");
			builder.put(grammarAccess.getLocationAccess().getYAssignment_6(), "rule__Location__YAssignment_6");
			builder.put(grammarAccess.getLocationAccess().getDescriptionAssignment_7_2(), "rule__Location__DescriptionAssignment_7_2");
			builder.put(grammarAccess.getPathsAccess().getLoc1Assignment_1(), "rule__Paths__Loc1Assignment_1");
			builder.put(grammarAccess.getPathsAccess().getLoc2Assignment_3(), "rule__Paths__Loc2Assignment_3");
			builder.put(grammarAccess.getPathsAccess().getDistanceAssignment_5(), "rule__Paths__DistanceAssignment_5");
			builder.put(grammarAccess.getPathsAccess().getSuccessAssignment_6_3(), "rule__Paths__SuccessAssignment_6_3");
			builder.put(grammarAccess.getAtomicTaskAccess().getNameAssignment_0(), "rule__AtomicTask__NameAssignment_0");
			builder.put(grammarAccess.getAtomicTaskAccess().getRobotsAssignment_2(), "rule__AtomicTask__RobotsAssignment_2");
			builder.put(grammarAccess.getAtomicTaskAccess().getLocAssignment_5_2(), "rule__AtomicTask__LocAssignment_5_2");
			builder.put(grammarAccess.getAtomicTaskAccess().getRetryAssignment_6_1(), "rule__AtomicTask__RetryAssignment_6_1");
			builder.put(grammarAccess.getCompoundTaskAccess().getNameAssignment_0(), "rule__CompoundTask__NameAssignment_0");
			builder.put(grammarAccess.getCompoundTaskAccess().getCanDoTaskAssignment_4_0(), "rule__CompoundTask__CanDoTaskAssignment_4_0");
			builder.put(grammarAccess.getCompoundTaskAccess().getCanDoTaskAssignment_4_1_1(), "rule__CompoundTask__CanDoTaskAssignment_4_1_1");
			builder.put(grammarAccess.getCompoundTaskAccess().getOrderedAssignment_6_0_1(), "rule__CompoundTask__OrderedAssignment_6_0_1");
			builder.put(grammarAccess.getCompoundTaskAccess().getConsecutiveAssignment_6_1_1(), "rule__CompoundTask__ConsecutiveAssignment_6_1_1");
			builder.put(grammarAccess.getRobotAccess().getNameAssignment_0(), "rule__Robot__NameAssignment_0");
			builder.put(grammarAccess.getRobotAccess().getInitLocAssignment_5(), "rule__Robot__InitLocAssignment_5");
			builder.put(grammarAccess.getRobotAccess().getVelocityAssignment_8(), "rule__Robot__VelocityAssignment_8");
			builder.put(grammarAccess.getRobotAccess().getCapabilitiesAssignment_12(), "rule__Robot__CapabilitiesAssignment_12");
			builder.put(grammarAccess.getRobotAccess().getCapabilitiesAssignment_13_1(), "rule__Robot__CapabilitiesAssignment_13_1");
			builder.put(grammarAccess.getCapabilityAccess().getAtAssignment_0(), "rule__Capability__AtAssignment_0");
			builder.put(grammarAccess.getCapabilityAccess().getTimeAssignment_3(), "rule__Capability__TimeAssignment_3");
			builder.put(grammarAccess.getCapabilityAccess().getSuccessAssignment_7(), "rule__Capability__SuccessAssignment_7");
			builder.put(grammarAccess.getMissionAccess().getMissionTaskAssignment_0(), "rule__Mission__MissionTaskAssignment_0");
			builder.put(grammarAccess.getMissionAccess().getMissionTaskAssignment_1_1(), "rule__Mission__MissionTaskAssignment_1_1");
			builder.put(grammarAccess.getMissionAccess().getObjAssignment_3(), "rule__Mission__ObjAssignment_3");
			builder.put(grammarAccess.getMissionAccess().getObjAssignment_4_1(), "rule__Mission__ObjAssignment_4_1");
			builder.put(grammarAccess.getMissionAccess().getConstraintsAssignment_5_1(), "rule__Mission__ConstraintsAssignment_5_1");
			builder.put(grammarAccess.getMissionAccess().getConstraintsAssignment_5_2_1(), "rule__Mission__ConstraintsAssignment_5_2_1");
			builder.put(grammarAccess.getMissionAccess().getTimeAssignment_6_1_1(), "rule__Mission__TimeAssignment_6_1_1");
			builder.put(grammarAccess.getMissionAccess().getNumAllocAssignment_6_2_1(), "rule__Mission__NumAllocAssignment_6_2_1");
			builder.put(grammarAccess.getMissionAccess().getPopulationAssignment_6_3_1(), "rule__Mission__PopulationAssignment_6_3_1");
			builder.put(grammarAccess.getMissionAccess().getEvaluationsAssignment_6_4_1(), "rule__Mission__EvaluationsAssignment_6_4_1");
			builder.put(grammarAccess.getMissionTaskAccess().getNameAssignment_1(), "rule__MissionTask__NameAssignment_1");
			builder.put(grammarAccess.getMissionTaskAccess().getAtAssignment_3_0_2(), "rule__MissionTask__AtAssignment_3_0_2");
			builder.put(grammarAccess.getMissionTaskAccess().getCtAssignment_3_1_2(), "rule__MissionTask__CtAssignment_3_1_2");
			builder.put(grammarAccess.getMissionTaskAccess().getLocAssignment_4_2(), "rule__MissionTask__LocAssignment_4_2");
			builder.put(grammarAccess.getRateSuccAccess().getRateSuccAssignment_1_5(), "rule__RateSucc__RateSuccAssignment_1_5");
			builder.put(grammarAccess.getSpaceXYRobotAccess().getRobotAssignment_0_0_1(), "rule__SpaceXYRobot__RobotAssignment_0_0_1");
			builder.put(grammarAccess.getSpaceXYRobotAccess().getAllrobotsAssignment_0_1_0(), "rule__SpaceXYRobot__AllrobotsAssignment_0_1_0");
			builder.put(grammarAccess.getSpaceXYRobotAccess().getCoordinateAssignment_3(), "rule__SpaceXYRobot__CoordinateAssignment_3");
			builder.put(grammarAccess.getSpaceXYRobotAccess().getLowerGreaterAssignment_4(), "rule__SpaceXYRobot__LowerGreaterAssignment_4");
			builder.put(grammarAccess.getSpaceXYRobotAccess().getValAssignment_6(), "rule__SpaceXYRobot__ValAssignment_6");
			builder.put(grammarAccess.getTaskTimeAccess().getAtAssignment_0_0_2(), "rule__TaskTime__AtAssignment_0_0_2");
			builder.put(grammarAccess.getTaskTimeAccess().getCtAssignment_0_1_2(), "rule__TaskTime__CtAssignment_0_1_2");
			builder.put(grammarAccess.getTaskTimeAccess().getMtAssignment_0_2_2(), "rule__TaskTime__MtAssignment_0_2_2");
			builder.put(grammarAccess.getTaskTimeAccess().getStartEndAssignment_3(), "rule__TaskTime__StartEndAssignment_3");
			builder.put(grammarAccess.getTaskTimeAccess().getTimeAssignment_5(), "rule__TaskTime__TimeAssignment_5");
			builder.put(grammarAccess.getAllocateTAccess().getAtAssignment_1_0_2(), "rule__AllocateT__AtAssignment_1_0_2");
			builder.put(grammarAccess.getAllocateTAccess().getCtAssignment_1_1_2(), "rule__AllocateT__CtAssignment_1_1_2");
			builder.put(grammarAccess.getAllocateTAccess().getMtAssignment_1_2_2(), "rule__AllocateT__MtAssignment_1_2_2");
			builder.put(grammarAccess.getAllocateTAccess().getRobotAssignment_3_0_1(), "rule__AllocateT__RobotAssignment_3_0_1");
			builder.put(grammarAccess.getClosestAccess().getAllAssignment_2_0_0(), "rule__Closest__AllAssignment_2_0_0");
			builder.put(grammarAccess.getClosestAccess().getAtAssignment_2_1_2(), "rule__Closest__AtAssignment_2_1_2");
			builder.put(grammarAccess.getClosestAccess().getCtAssignment_2_2_2(), "rule__Closest__CtAssignment_2_2_2");
			builder.put(grammarAccess.getClosestAccess().getMtAssignment_2_3_2(), "rule__Closest__MtAssignment_2_3_2");
			builder.put(grammarAccess.getMaxTasksAccess().getAllAssignment_5_0_0(), "rule__MaxTasks__AllAssignment_5_0_0");
			builder.put(grammarAccess.getMaxTasksAccess().getRobotAssignment_5_1_2(), "rule__MaxTasks__RobotAssignment_5_1_2");
			builder.put(grammarAccess.getMaxTasksAccess().getNumAssignment_7(), "rule__MaxTasks__NumAssignment_7");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
